const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let state={csrf:'',user:null};
async function api(path,opts={}){opts.headers={...(opts.headers||{})};if(opts.body){opts.headers['Content-Type']='application/json'}if(state.csrf&&opts.method&&opts.method!=='GET')opts.headers['X-CSRF-Token']=state.csrf;const r=await fetch(path,opts);let data=null;try{data=await r.json()}catch{}if(r.status===401&&path!='/api/login'){showLogin();throw new Error('登录已过期')}if(!r.ok)throw new Error(data?.error||`请求失败 (${r.status})`);return data}
function showLogin(){$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
function showApp(data){state=data;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#username').textContent=data.user.Username;$('#role').textContent=data.user.Role;$('#avatar').textContent=data.user.Username[0].toUpperCase();$$('.admin-only').forEach(x=>x.classList.toggle('hidden',data.user.Role!=='admin'));checkHealth()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const fd=new FormData(e.target);try{showApp(await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(fd))}))}catch(err){$('#loginError').textContent=err.message}})
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST'})}finally{state={csrf:'',user:null};showLogin()}};
const views={query:['SQL 工作台','查询并管理 ClickHouse 数据'],schema:['对象浏览器','浏览数据库和数据表'],users:['用户管理','管理控制台账号与角色'],audit:['审计日志','追踪关键操作与执行结果']};
$$('nav button').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.add('hidden'));$(`#${v}View`).classList.remove('hidden');$('#title').textContent=views[v][0];$('#subtitle').textContent=views[v][1];if(v==='schema')loadDatabases();if(v==='users')loadUsers();if(v==='audit')loadAudit()});
async function checkHealth(){try{await api('/api/health');$('#health').className='health ok';$('#health span').textContent='ClickHouse 已连接'}catch(e){$('#health').className='health bad';$('#health span').textContent='ClickHouse 连接失败'}}
$('#run').onclick=runQuery;$('#sql').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();runQuery()}});$('#format').onclick=()=>{$('#sql').value=$('#sql').value.trim().replace(/\s+(FROM|WHERE|GROUP BY|ORDER BY|LIMIT|SETTINGS|FORMAT)\s+/gi,'\n$1 ')};
async function runQuery(){const sql=$('#sql').value.trim();if(!sql)return;$('#run').disabled=true;$('#run').textContent='执行中…';$('#queryStatus').className='status hidden';try{const r=await api('/api/query',{method:'POST',body:JSON.stringify({sql})});$('#queryStatus').className='status ok';$('#queryStatus').textContent=`执行成功 · ${r.elapsed_ms} ms`;$('#resultMeta').textContent=r.kind==='query'?`${r.rows||0} 行 · ${r.elapsed_ms} ms`:`${r.kind.toUpperCase()} 执行成功`;renderResult(r)}catch(e){$('#queryStatus').className='status error';$('#queryStatus').textContent=e.message}finally{$('#run').disabled=false;$('#run').innerHTML='▶ 运行 <kbd>⌘↵</kbd>'}}
function renderResult(r){if(!r.meta?.length){$('#result').className='empty';$('#result').textContent='命令执行成功';return}const cols=r.meta.map(x=>x.name);$('#result').className='table-wrap';$('#result').innerHTML=`<table><thead><tr>${r.meta.map(x=>`<th title="${esc(x.type)}">${esc(x.name)}</th>`).join('')}</tr></thead><tbody>${(r.data||[]).map(row=>`<tr>${cols.map(c=>`<td class="code">${esc(value(row[c]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function loadDatabases(){try{const r=await api('/api/query',{method:'POST',body:JSON.stringify({sql:"SELECT name FROM system.databases ORDER BY name"})});$('#databases').innerHTML=r.data.map(x=>`<button data-db="${esc(x.name)}">▱ &nbsp;${esc(x.name)}</button>`).join('');$$('#databases button').forEach(b=>b.onclick=()=>loadTables(b.dataset.db,b))}catch(e){toast(e.message)}}
async function loadTables(db,btn){$$('#databases button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#tablesTitle').textContent=`${db} / 数据表`;try{const safe=db.replaceAll("'","''");const r=await api('/api/query',{method:'POST',body:JSON.stringify({sql:`SELECT name, engine, total_rows FROM system.tables WHERE database='${safe}' ORDER BY name`})});$('#tables').innerHTML=r.data.length?r.data.map(x=>`<div class="row"><strong>▦ ${esc(x.name)}</strong><small>${esc(x.engine)} · ${esc(value(x.total_rows))} rows</small></div>`).join(''):'<div class="empty">暂无数据表</div>'}catch(e){toast(e.message)}}
$('#refreshSchema').onclick=loadDatabases;
async function loadUsers(){try{const users=await api('/api/users');$('#userRows').innerHTML=users.map(u=>`<tr><td><strong>${esc(u.Username)}</strong></td><td><span class="tag">${esc(u.Role)}</span></td><td><span class="tag ${u.Disabled?'error':'ok'}">${u.Disabled?'已停用':'正常'}</span></td><td>${date(u.CreatedAt)}</td><td>${u.ID===state.user.ID?'当前账号':`<button class="ghost toggle-user" data-id="${u.ID}" data-disabled="${u.Disabled}">${u.Disabled?'启用':'停用'}</button>`}</td></tr>`).join('');$$('.toggle-user').forEach(b=>b.onclick=async()=>{try{await api('/api/users/'+b.dataset.id,{method:'PATCH',body:JSON.stringify({Disabled:b.dataset.disabled!=='true'})});loadUsers()}catch(e){toast(e.message)}})}catch(e){toast(e.message)}}
$('#newUser').onclick=()=>{$('#userForm').reset();$('#userError').textContent='';$('#userDialog').showModal()};$$('.close').forEach(x=>x.onclick=()=>$('#userDialog').close());$('#userForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{await api('/api/users',{method:'POST',body:JSON.stringify(body)});$('#userDialog').close();loadUsers();toast('用户已创建')}catch(err){$('#userError').textContent=err.message}};
async function loadAudit(){try{const rows=await api('/api/audit?limit=500');$('#auditRows').innerHTML=rows.map(a=>`<tr><td>${date(a.At)}</td><td>${esc(a.User||'—')}</td><td>${esc(a.Action)}</td><td><span class="tag ${a.Status==='ok'?'ok':'error'}">${esc(a.Status)}</span></td><td>${a.DurationMS||0} ms</td><td class="code" title="${esc(a.Error||a.Statement)}">${esc(a.Error||a.Statement||'—')}</td></tr>`).join('')}catch(e){toast(e.message)}}$('#refreshAudit').onclick=loadAudit;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function value(v){return typeof v==='object'?JSON.stringify(v):String(v??'NULL')}function date(v){return new Date(v).toLocaleString()}function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
(async()=>{try{showApp(await api('/api/session'))}catch{showLogin()}})();
